### ISSUE TITLE
"at the start of every quarter" could not be translated

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#176]
Something is going wrong with the translation of the label to a value. Is there a test case covering this? This causes crashes in the worker. Probably an easy fix, and probably also in the new version.

```
[2020-06-16 12:16:00,082: INFO/ForkPoolWorker-8] Task websecmap.app.models.create_function_job[25071366-502a-4aa4-bf16-983e90550b74] succeeded in 0.07154172006994486s: <Job: dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.check_running_dashboard_scans>
[2020-06-16 12:16:00,085: INFO/ForkPoolWorker-9] Task websecmap.app.models.store_result[ac5042b4-0d3e-4e15-8fe8-21eaa5d4eb87] succeeded in 0.018189022317528725s: None
[2020-06-16 12:16:00,316: ERROR/ForkPoolWorker-1] Task websecmap.app.models.create_function_job[e92e58fb-3ac8-45c0-a9d2-80b251cb5a7c] raised unexpected: ValueError('String at the start of every quarter could not be translated to a scan moment.')
Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/websecmap/app/models.py", line 127, in create_function_job
    task = call(**kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 651, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
  File "/source/dashboard/internet_nl_dashboard/tasks.py", line 40, in start_scans_for_lists_who_are_up_for_scanning
    urllist.renew_scan_moment()
  File "/source/dashboard/internet_nl_dashboard/models.py", line 216, in renew_scan_moment
    self.scheduled_next_scan = self.determine_next_scan_moment(self.automated_scan_frequency)
  File "/source/dashboard/internet_nl_dashboard/models.py", line 271, in determine_next_scan_moment
    raise ValueError('String %s could not be translated to a scan moment.' % preference)
ValueError: String at the start of every quarter could not be translated to a scan moment.
```

**Comment by stitch** [comment]
Fixed including tests.
