### ISSUE TITLE
Scans hang after two months

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#206]
The following two exceptions i've seen. There is no direct cause for the first issue it seems (the actual hang). Perhaps a bug in the stack.

While hanging:
```
[2020-09-22 08:56:26,443: INFO/ForkPoolWorker-8] Task websecmap.app.models.create_function_job[e6421b0e-d49c-4037-9422-64f5d589d76c] succeeded in 0.05573022086173296s: <Job: dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.check_running_dashboard_scans>
[2020-09-22 08:56:26,445: WARNING/ForkPoolWorker-8] Exception ignored in:
[2020-09-22 08:56:26,445: WARNING/ForkPoolWorker-8] <function AsyncResult.__del__ at 0x7f36a54dfb00>
[2020-09-22 08:56:26,445: WARNING/ForkPoolWorker-8] Traceback (most recent call last):
[2020-09-22 08:56:26,445: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 389, in __del__
[2020-09-22 08:56:26,446: WARNING/ForkPoolWorker-8] self.backend.remove_pending_result(self)
[2020-09-22 08:56:26,446: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 180, in remove_pending_result
[2020-09-22 08:56:26,447: WARNING/ForkPoolWorker-8] self.on_result_fulfilled(result)
[2020-09-22 08:56:26,447: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 188, in on_result_fulfilled
[2020-09-22 08:56:26,447: WARNING/ForkPoolWorker-8] self.result_consumer.cancel_for(result.id)
[2020-09-22 08:56:26,447: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/redis.py", line 148, in cancel_for
[2020-09-22 08:56:26,447: WARNING/ForkPoolWorker-8] self._pubsub.unsubscribe(key)
[2020-09-22 08:56:26,447: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3548, in unsubscribe
2020-09-22 08:56	INFO     - Task websecmap.app.models.store_result[4b9a9e9e-fa9b-49e0-83c8-e245d92a4172] succeeded in 0.01689216122031212s: None
[2020-09-22 08:56:26,449: INFO/ForkPoolWorker-1] Task websecmap.app.models.store_result[4b9a9e9e-fa9b-49e0-83c8-e245d92a4172] succeeded in 0.01689216122031212s: None
[2020-09-22 08:56:26,449: WARNING/ForkPoolWorker-8] return self.execute_command('UNSUBSCRIBE', *args)
[2020-09-22 08:56:26,449: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3423, in execute_command
[2020-09-22 08:56:26,451: WARNING/ForkPoolWorker-8] self._execute(connection, connection.send_command, *args, **kwargs)
[2020-09-22 08:56:26,451: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute
[2020-09-22 08:56:26,453: WARNING/ForkPoolWorker-8] return command(*args, **kwargs)
[2020-09-22 08:56:26,453: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 721, in send_command
[2020-09-22 08:56:26,454: WARNING/ForkPoolWorker-8] check_health=kwargs.get('check_health', True))
[2020-09-22 08:56:26,454: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 713, in send_packed_command
[2020-09-22 08:56:26,454: WARNING/ForkPoolWorker-8] (errno, errmsg))
[2020-09-22 08:56:26,455: WARNING/ForkPoolWorker-8] redis.exceptions
[2020-09-22 08:56:26,455: WARNING/ForkPoolWorker-8] .
[2020-09-22 08:56:26,455: WARNING/ForkPoolWorker-8] ConnectionError
[2020-09-22 08:56:26,455: WARNING/ForkPoolWorker-8] :
[2020-09-22 08:56:26,455: WARNING/ForkPoolWorker-8] Error 104 while writing to socket. Connection reset by peer.


[2020-09-22 08:58:03,333: INFO/ForkPoolWorker-8] Task websecmap.app.models.create_function_job[34a920ab-9af5-4bc9-b1b8-57505b87c7f7] succeeded in 0.04028371721506119s: <Job: dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.check_running_dashboard_scans>
[2020-09-22 08:58:03,334: WARNING/ForkPoolWorker-8] Exception ignored in:
[2020-09-22 08:58:03,334: WARNING/ForkPoolWorker-8] <function AsyncResult.__del__ at 0x7f36a54dfb00>
[2020-09-22 08:58:03,334: WARNING/ForkPoolWorker-8] Traceback (most recent call last):
[2020-09-22 08:58:03,334: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 389, in __del__
[2020-09-22 08:58:03,335: WARNING/ForkPoolWorker-8] self.backend.remove_pending_result(self)
[2020-09-22 08:58:03,335: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 180, in remove_pending_result
[2020-09-22 08:58:03,335: WARNING/ForkPoolWorker-8] self.on_result_fulfilled(result)
[2020-09-22 08:58:03,335: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 188, in on_result_fulfilled
[2020-09-22 08:58:03,336: WARNING/ForkPoolWorker-8] self.result_consumer.cancel_for(result.id)
[2020-09-22 08:58:03,336: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/redis.py", line 148, in cancel_for
[2020-09-22 08:58:03,336: WARNING/ForkPoolWorker-8] self._pubsub.unsubscribe(key)
[2020-09-22 08:58:03,337: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3548, in unsubscribe
[2020-09-22 08:58:03,338: WARNING/ForkPoolWorker-8] return self.execute_command('UNSUBSCRIBE', *args)
[2020-09-22 08:58:03,339: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3423, in execute_command
[2020-09-22 08:58:03,341: WARNING/ForkPoolWorker-8] self._execute(connection, connection.send_command, *args, **kwargs)
[2020-09-22 08:58:03,341: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute
2020-09-22 08:58	INFO     - Task websecmap.app.models.store_result[fcc99a5b-a79d-4efb-9d67-9c71981889cd] succeeded in 0.013317691162228584s: None
[2020-09-22 08:58:03,343: INFO/ForkPoolWorker-9] Task websecmap.app.models.store_result[fcc99a5b-a79d-4efb-9d67-9c71981889cd] succeeded in 0.013317691162228584s: None
[2020-09-22 08:58:03,343: WARNING/ForkPoolWorker-8] return command(*args, **kwargs)
[2020-09-22 08:58:03,343: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 721, in send_command
[2020-09-22 08:58:03,345: WARNING/ForkPoolWorker-8] check_health=kwargs.get('check_health', True))
[2020-09-22 08:58:03,345: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 713, in send_packed_command
[2020-09-22 08:58:03,345: WARNING/ForkPoolWorker-8] (errno, errmsg))
[2020-09-22 08:58:03,345: WARNING/ForkPoolWorker-8] redis.exceptions
[2020-09-22 08:58:03,345: WARNING/ForkPoolWorker-8] .
[2020-09-22 08:58:03,346: WARNING/ForkPoolWorker-8] ConnectionError
[2020-09-22 08:58:03,346: WARNING/ForkPoolWorker-8] :
[2020-09-22 08:58:03,346: WARNING/ForkPoolWorker-8] Error 104 while writing to socket. Connection reset by peer.

[2020-09-22 08:59:30,098: INFO/ForkPoolWorker-8] Task websecmap.app.models.create_function_job[754eb8d4-b3b0-42c4-9ab5-7d5912b879a3] succeeded in 0.05797881539911032s: <Job: dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.check_running_dashboard_scans>
[2020-09-22 08:59:30,099: WARNING/ForkPoolWorker-8] Exception ignored in:
[2020-09-22 08:59:30,100: WARNING/ForkPoolWorker-8] <function AsyncResult.__del__ at 0x7f36a54dfb00>
[2020-09-22 08:59:30,100: WARNING/ForkPoolWorker-8] Traceback (most recent call last):
[2020-09-22 08:59:30,100: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 389, in __del__
[2020-09-22 08:59:30,100: WARNING/ForkPoolWorker-8] self.backend.remove_pending_result(self)
[2020-09-22 08:59:30,100: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 180, in remove_pending_result
[2020-09-22 08:59:30,101: WARNING/ForkPoolWorker-8] self.on_result_fulfilled(result)
[2020-09-22 08:59:30,101: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 188, in on_result_fulfilled
[2020-09-22 08:59:30,101: WARNING/ForkPoolWorker-8] self.result_consumer.cancel_for(result.id)
[2020-09-22 08:59:30,101: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/redis.py", line 148, in cancel_for
[2020-09-22 08:59:30,101: WARNING/ForkPoolWorker-8] self._pubsub.unsubscribe(key)
[2020-09-22 08:59:30,101: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3548, in unsubscribe
[2020-09-22 08:59:30,103: WARNING/ForkPoolWorker-8] return self.execute_command('UNSUBSCRIBE', *args)
[2020-09-22 08:59:30,103: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3423, in execute_command
[2020-09-22 08:59:30,104: WARNING/ForkPoolWorker-8] self._execute(connection, connection.send_command, *args, **kwargs)
[2020-09-22 08:59:30,104: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute
[2020-09-22 08:59:30,106: WARNING/ForkPoolWorker-8] return command(*args, **kwargs)
[2020-09-22 08:59:30,106: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 721, in send_command
[2020-09-22 08:59:30,107: WARNING/ForkPoolWorker-8] check_health=kwargs.get('check_health', True))
[2020-09-22 08:59:30,107: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 713, in send_packed_command
[2020-09-22 08:59:30,107: WARNING/ForkPoolWorker-8] (errno, errmsg))
[2020-09-22 08:59:30,108: WARNING/ForkPoolWorker-8] redis.exceptions
[2020-09-22 08:59:30,108: WARNING/ForkPoolWorker-8] .
[2020-09-22 08:59:30,108: WARNING/ForkPoolWorker-8] ConnectionError
[2020-09-22 08:59:30,108: WARNING/ForkPoolWorker-8] :
[2020-09-22 08:59:30,108: WARNING/ForkPoolWorker-8] Error 104 while writing to socket. Connection reset by peer.
```

After restart, rolling back all open tasks:
```
[2020-09-22 09:18:04,261: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fc176171cb0> (args:('websecmap.app.models.store_result', '8bf70598-6f0a-45a6-86ea-1b836181720b', {'lang': 'py', 'task': 'websecmap.app.models.store_result', 'id': '8bf70598-6f0a-45a6-86ea-1b836181720b', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'fc6f18ef-2cfe-4d75-b23e-fb3be98727a2', 'parent_id': 'fc6f18ef-2cfe-4d75-b23e-fb3be98727a2', 'argsrepr': '([],)', 'kwargsrepr': "{'job_id': 1856833}", 'origin': 'gen444@14ed9ae498f6', 'reply_to': '699545eb-4a45-3520-a576-490c19d5864b', 'correlation_id': '8bf70598-6f0a-45a6-86ea-1b836181720b', 'hostname': 'default@14ed9ae498f6', 'delivery_info': {'exchange': '', 'routing_key': 'storage', 'priority': 5, 'redelivered': None}, 'args': ([],), 'kwargs': {'job_id': 1856833}}, b'\x80\x02]q\x00\x85q\x01}q\x02X\x06\x00\x00\x00job_idq\x03JAU\x1c\x00s}q\x04(X\t\x00\x00\x00callbacksq\x05NX\x08\x00\x00\x00errbacksq\x06NX\x05\x00\x00\x00chainq\x07NX\x05\x00\x00\x00chordq\x08Nu\x87q\t.', 'application/x-python-serialize', 'binary') kwargs:{})
[2020-09-22 09:18:04,261: DEBUG/MainProcess] Task accepted: dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.recover_and_retry[f429d52f-ada1-41f7-ba1a-1eb3acd86fee] pid:441
[2020-09-22 09:18:04,262: DEBUG/MainProcess] Task accepted: dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.recover_and_retry[cd3a0446-5b7e-49d7-bb36-54daa8c1783f] pid:442
2020-09-22 09:18	DEBUG    - Internet.nl scan #1215 state changed from 'storing scan results' to 'scan results ready'.
[2020-09-22 09:18:04,263: DEBUG/ForkPoolWorker-10] Internet.nl scan #1215 state changed from 'storing scan results' to 'scan results ready'.
[2020-09-22 09:18:04,266: DEBUG/MainProcess] Task accepted: websecmap.app.models.store_result[8bf70598-6f0a-45a6-86ea-1b836181720b] pid:443
2020-09-22 09:18	INFO     - Task dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.recover_and_retry[156f4725-71d5-4653-8b09-0cfa05e4abcf] succeeded in 0.07798400799998717s: {'task': 'celery.group''args': ()'kwargs': {'tasks': []}'options': {}'subtask_type': 'group''immutable': False'chord_size': None}
[2020-09-22 09:18:04,266: INFO/ForkPoolWorker-10] Task dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.recover_and_retry[156f4725-71d5-4653-8b09-0cfa05e4abcf] succeeded in 0.07798400799998717s: {'task': 'celery.group''args': ()'kwargs': {'tasks': []}'options': {}'subtask_type': 'group''immutable': False'chord_size': None}
2020-09-22 09:18	DEBUG    - AccountInternetNLScan scan #1209 is rolled back to retry from 'creating report' to 'scan results ready'.
[2020-09-22 09:18:04,298: DEBUG/ForkPoolWorker-6] AccountInternetNLScan scan #1209 is rolled back to retry from 'creating report' to 'scan results ready'.
2020-09-22 09:18	DEBUG    - AccountInternetNLScan scan #1211 is rolled back to retry from 'creating report' to 'scan results ready'.
[2020-09-22 09:18:04,303: DEBUG/ForkPoolWorker-5] AccountInternetNLScan scan #1211 is rolled back to retry from 'creating report' to 'scan results ready'.
2020-09-22 09:18	INFO     - Task websecmap.app.models.store_result[8bf70598-6f0a-45a6-86ea-1b836181720b] succeeded in 0.048965301999999156s: None
[2020-09-22 09:18:04,314: INFO/ForkPoolWorker-7] Task websecmap.app.models.store_result[8bf70598-6f0a-45a6-86ea-1b836181720b] succeeded in 0.048965301999999156s: None
2020-09-22 09:18	ERROR    - Task dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.recover_and_retry[f5f728da-10b7-418c-82c3-4e50fcf2cc05] raised unexpected: AttributeError("'NoneType' object has no attribute 'state'")
Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/source/dashboard/internet_nl_dashboard/scanners/scan_internet_nl_per_account.py", line 272, in recover_and_retry
    internet_nl_v2_websecmap.recover_and_retry(scan.scan)
  File "/pyenv/lib/python3.7/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 651, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/websecmap/scanners/scanner/internet_nl_v2_websecmap.py", line 195, in recover_and_retry
    log.debug(f"Internet.nl scan #{scan.id} is rolled back to retry from '{scan.state}' to '{latest_valid.state}'.")
AttributeError: 'NoneType' object has no attribute 'state'
2020-09-22 09:18	ERROR    - Task dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.recover_and_retry[7c9f1e12-0fcd-46a5-b707-f0d4b84576a4] raised unexpected: AttributeError("'NoneType' object has no attribute 'state'")
Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/source/dashboard/internet_nl_dashboard/scanners/scan_internet_nl_per_account.py", line 272, in recover_and_retry
    internet_nl_v2_websecmap.recover_and_retry(scan.scan)
  File "/pyenv/lib/python3.7/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 651, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/websecmap/scanners/scanner/internet_nl_v2_websecmap.py", line 195, in recover_and_retry
    log.debug(f"Internet.nl scan #{scan.id} is rolled back to retry from '{scan.state}' to '{latest_valid.state}'.")
AttributeError: 'NoneType' object has no attribute 'state'
[2020-09-22 09:18:04,321: ERROR/ForkPoolWorker-4] Task dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.recover_and_retry[7c9f1e12-0fcd-46a5-b707-f0d4b84576a4] raised unexpected: AttributeError("'NoneType' object has no attribute 'state'")
Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/source/dashboard/internet_nl_dashboard/scanners/scan_internet_nl_per_account.py", line 272, in recover_and_retry
    internet_nl_v2_websecmap.recover_and_retry(scan.scan)
  File "/pyenv/lib/python3.7/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 651, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/websecmap/scanners/scanner/internet_nl_v2_websecmap.py", line 195, in recover_and_retry
    log.debug(f"Internet.nl scan #{scan.id} is rolled back to retry from '{scan.state}' to '{latest_valid.state}'.")
AttributeError: 'NoneType' object has no attribute 'state'
[2020-09-22 09:18:04,319: ERROR/ForkPoolWorker-8] Task dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.recover_and_retry[f5f728da-10b7-418c-82c3-4e50fcf2cc05] raised unexpected: AttributeError("'NoneType' object has no attribute 'state'")
Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/source/dashboard/internet_nl_dashboard/scanners/scan_internet_nl_per_account.py", line 272, in recover_and_retry
    internet_nl_v2_websecmap.recover_and_retry(scan.scan)
  File "/pyenv/lib/python3.7/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 651, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/websecmap/scanners/scanner/internet_nl_v2_websecmap.py", line 195, in recover_and_retry
    log.debug(f"Internet.nl scan #{scan.id} is rolled back to retry from '{scan.state}' to '{latest_valid.state}'.")
AttributeError: 'NoneType' object has no attribute 'state'
2020-09-22 09:18	DEBUG    - Internet.nl scan #1214 is rolled back to retry from 'processing scan results' to 'scan results stored'.
2020-09-22 09:18	DEBUG    - Internet.nl scan #1209 is rolled back to retry from 'finished' to 'scan results stored'.
[2020-09-22 09:18:04,396: DEBUG/ForkPoolWorker-6] Internet.nl scan #1209 is rolled back to retry from 'finished' to 'scan results stored'.
[2020-09-22 09:18:04,386: DEBUG/ForkPoolWorker-3] Internet.nl scan #1214 is rolled back to retry from 'processing scan results' to 'scan results stored'.
2020-09-22 09:18	DEBUG    - Internet.nl scan #1217 is rolled back to retry from 'finished' to 'scan results stored'.
[2020-09-22 09:18:04,452: DEBUG/ForkPoolWorker-9] Internet.nl scan #1217 is rolled back to retry from 'finished' to 'scan results stored'.
2020-09-22 09:18	DEBUG    - Internet.nl scan #1218 is rolled back to retry from 'processing scan results' to 'scan results stored'.
[2020-09-22 09:18:04,460: DEBUG/ForkPoolWorker-1] Internet.nl scan #1218 is rolled back to retry from 'processing scan results' to 'scan results stored'.
2020-09-22 09:18	DEBUG    - Internet.nl scan #1214 state changed from 'processing scan results' to 'scan results stored'.
[2020-09-22 09:18:04,522: DEBUG/ForkPoolWorker-3] Internet.nl scan #1214 state changed from 'processing scan results' to 'scan results stored'.
2020-09-22 09:18	DEBUG    - Internet.nl scan #1209 state changed from 'finished' to 'scan results stored'.
[2020-09-22 09:18:04,523: DEBUG/ForkPoolWorker-6] Internet.nl scan #1209 state changed from 'finished' to 'scan results stored'.
```

**Comment by stitch** [comment]
Solved in last bug fixes.
