### ISSUE TITLE
Unknown exceptions appearing in log

### ISSUE THREAD

**Issue by stitch** [internetstandards/Internet.nl-dashboard#212]
Regelmatig exception met hetzelfde rapport / talk #1265:
```
[2020-10-05 14:11:13,487: DEBUG/ForkPoolWorker-8] Internet.nl scan #1250 is being progressed from running scan.
2020-10-05 14:11	DEBUG    - Internet.nl scan #1265 is being progressed from running scan.
[2020-10-05 14:11:13,505: DEBUG/ForkPoolWorker-8] Internet.nl scan #1265 is being progressed from running scan.
2020-10-05 14:11	ERROR    - Task websecmap.app.models.create_function_job[3bc907fd-bd12-45b6-83c8-52e83713eb0f] raised unexpected: ConnectionError('Error 104 while writing to socket. Connection reset by peer.')
Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 159, in add_pending_result
    self._maybe_resolve_from_buffer(result)
  File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 165, in _maybe_resolve_from_buffer
    result._maybe_set_cache(self._pending_messages.take(result.id))
  File "/pyenv/lib/python3.7/site-packages/celery/utils/collections.py", line 884, in take
    raise self.Empty()
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 700, in send_packed_command
    sendall(self._sock, item)
  File "/pyenv/lib/python3.7/site-packages/redis/_compat.py", line 8, in sendall
    return sock.sendall(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/websecmap/app/models.py", line 129, in create_function_job
    return Job.create(task, function, None)
  File "/pyenv/lib/python3.7/site-packages/websecmap/app/models.py", line 80, in create
    result_id = (task | cls.store_result.s(job_id=job.id)).apply_async(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/canvas.py", line 1350, in apply_async
    return self.run(tasks, body, args, task_id=task_id, **options)
  File "/pyenv/lib/python3.7/site-packages/celery/canvas.py", line 1397, in run
    header_result = header.freeze(group_id=group_id, chord=body, root_id=root_id)
  File "/pyenv/lib/python3.7/site-packages/celery/canvas.py", line 1210, in freeze
    return self.app.GroupResult(gid, results)
  File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 911, in __init__
    ResultSet.__init__(self, results, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 538, in __init__
    self._on_full = ready_barrier or barrier(results)
  File "/pyenv/lib/python3.7/site-packages/vine/synchronization.py", line 57, in __init__
    [self.add_noincr(p) for p in promises or []]
  File "/pyenv/lib/python3.7/site-packages/vine/synchronization.py", line 57, in <listcomp>
    [self.add_noincr(p) for p in promises or []]
  File "/pyenv/lib/python3.7/site-packages/vine/synchronization.py", line 82, in add_noincr
    p.then(self)
  File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 121, in then
    self.backend.add_pending_result(self, weak=weak)
  File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 161, in add_pending_result
    self._add_pending_result(result.id, result, weak=weak)
  File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 171, in _add_pending_result
    self.result_consumer.consume_from(task_id)
  File "/pyenv/lib/python3.7/site-packages/celery/backends/redis.py", line 136, in consume_from
    self._consume_from(task_id)
  File "/pyenv/lib/python3.7/site-packages/celery/backends/redis.py", line 142, in _consume_from
    self._pubsub.subscribe(key)
  File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3528, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3423, in execute_command
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute
    return command(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 721, in send_command
    check_health=kwargs.get('check_health', True))
  File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 713, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.
[2020-10-05 14:11:13,545: ERROR/ForkPoolWorker-8] Task websecmap.app.models.create_function_job[3bc907fd-bd12-45b6-83c8-52e83713eb0f] raised unexpected: ConnectionError('Error 104 while writing to socket. Connection reset by peer.')
Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 159, in add_pending_result
    self._maybe_resolve_from_buffer(result)
  File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 165, in _maybe_resolve_from_buffer
    result._maybe_set_cache(self._pending_messages.take(result.id))
  File "/pyenv/lib/python3.7/site-packages/celery/utils/collections.py", line 884, in take
    raise self.Empty()
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 700, in send_packed_command
    sendall(self._sock, item)
  File "/pyenv/lib/python3.7/site-packages/redis/_compat.py", line 8, in sendall
    return sock.sendall(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/websecmap/app/models.py", line 129, in create_function_job
    return Job.create(task, function, None)
  File "/pyenv/lib/python3.7/site-packages/websecmap/app/models.py", line 80, in create
    result_id = (task | cls.store_result.s(job_id=job.id)).apply_async(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/canvas.py", line 1350, in apply_async
    return self.run(tasks, body, args, task_id=task_id, **options)
  File "/pyenv/lib/python3.7/site-packages/celery/canvas.py", line 1397, in run
    header_result = header.freeze(group_id=group_id, chord=body, root_id=root_id)
  File "/pyenv/lib/python3.7/site-packages/celery/canvas.py", line 1210, in freeze
    return self.app.GroupResult(gid, results)
  File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 911, in __init__
    ResultSet.__init__(self, results, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 538, in __init__
    self._on_full = ready_barrier or barrier(results)
  File "/pyenv/lib/python3.7/site-packages/vine/synchronization.py", line 57, in __init__
    [self.add_noincr(p) for p in promises or []]
  File "/pyenv/lib/python3.7/site-packages/vine/synchronization.py", line 57, in <listcomp>
    [self.add_noincr(p) for p in promises or []]
  File "/pyenv/lib/python3.7/site-packages/vine/synchronization.py", line 82, in add_noincr
    p.then(self)
  File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 121, in then
    self.backend.add_pending_result(self, weak=weak)
  File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 161, in add_pending_result
    self._add_pending_result(result.id, result, weak=weak)
  File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 171, in _add_pending_result
    self.result_consumer.consume_from(task_id)
  File "/pyenv/lib/python3.7/site-packages/celery/backends/redis.py", line 136, in consume_from
    self._consume_from(task_id)
  File "/pyenv/lib/python3.7/site-packages/celery/backends/redis.py", line 142, in _consume_from
    self._pubsub.subscribe(key)
  File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3528, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3423, in execute_command
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute
    return command(*args, **kwargs)
  File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 721, in send_command
    check_health=kwargs.get('check_health', True))
  File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 713, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.
[2020-10-05 14:11:21,719: INFO/MainProcess] Received task: websecmap.app.models.create_function_job[63e7e9a2-9e36-46a2-896d-90c2662a5eb6]  
[2020-10-05 14:11:21,719: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fc176171cb0> (args:('websecmap.app.models.create_function_job', '63e7e9a2-9e36-46a2-896d-90c2662a5eb6', {'lang': 'py', 'task': 'websecmap.app.models.create_function_job', 'id': '63e7e9a2-9e36-46a2-896d-90c2662a5eb6', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '63e7e9a2-9e36-46a2-896d-90c2662a5eb6', 'parent_id': None, 'argsrepr': "['dashboard.internet_nl_dashboard.scanners.scan_internet_nl_per_account.che
```

UNSUBSCRIBE error: Dit lijkt uit CELERY backend cleanup te komen.
```
2020-10-05 14:18	DEBUG    - On 2020-07-22 07:25:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
[2020-10-05 14:18:04,148: DEBUG/ForkPoolWorker-1] On 2020-07-22 07:25:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
2020-10-05 14:18	DEBUG    - On 2020-07-22 08:11:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
[2020-10-05 14:18:04,159: DEBUG/ForkPoolWorker-1] On 2020-07-22 08:11:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
2020-10-05 14:18	DEBUG    - On 2020-07-22 09:29:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
[2020-10-05 14:18:04,171: DEBUG/ForkPoolWorker-1] On 2020-07-22 09:29:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
2020-10-05 14:18	DEBUG    - On 2020-07-27 05:59:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
[2020-10-05 14:18:04,208: DEBUG/ForkPoolWorker-1] On 2020-07-27 05:59:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
[2020-10-05 14:18:04,209: INFO/MainProcess] Received task: websecmap.app.models.store_result[8c282899-3fdd-4d00-b706-8d5f09d1ec14]  
[2020-10-05 14:18:04,210: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fc176171cb0> (args:('websecmap.app.models.store_result', '8c282899-3fdd-4d00-b706-8d5f09d1ec14', {'lang': 'py', 'task': 'websecmap.app.models.store_result', 'id': '8c282899-3fdd-4d00-b706-8d5f09d1ec14', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '3574e7c3-6ac7-4f38-88f2-2041051bc251', 'parent_id': '3574e7c3-6ac7-4f38-88f2-2041051bc251', 'argsrepr': '([],)', 'kwargsrepr': "{'job_id': 1989846}", 'origin': 'gen444@14ed9ae498f6', 'reply_to': '699545eb-4a45-3520-a576-490c19d5864b', 'correlation_id': '8c282899-3fdd-4d00-b706-8d5f09d1ec14', 'hostname': 'default@14ed9ae498f6', 'delivery_info': {'exchange': '', 'routing_key': 'storage', 'priority': 5, 'redelivered': None}, 'args': ([],), 'kwargs': {'job_id': 1989846}}, b'\x80\x02]q\x00\x85q\x01}q\x02X\x06\x00\x00\x00job_idq\x03J\xd6\\\x1e\x00s}q\x04(X\t\x00\x00\x00callbacksq\x05NX\x08\x00\x00\x00errbacksq\x06NX\x05\x00\x00\x00chainq\x07NX\x05\x00\x00\x00chordq\x08Nu\x87q\t.', 'application/x-python-serialize',... kwargs:{})
[2020-10-05 14:18:04,212: DEBUG/MainProcess] Task accepted: websecmap.app.models.store_result[8c282899-3fdd-4d00-b706-8d5f09d1ec14] pid:445
2020-10-05 14:18	DEBUG    - On 2020-07-27 07:33:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
[2020-10-05 14:18:04,223: DEBUG/ForkPoolWorker-1] On 2020-07-27 07:33:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
2020-10-05 14:18	INFO     - Task websecmap.app.models.create_function_job[3574e7c3-6ac7-4f38-88f2-2041051bc251] succeeded in 4.220241545001045s: <Job: dashboard.internet_nl_dashboard.tasks.start_scans_for_lists_who_are_up_for_scanning>
[2020-10-05 14:18:04,235: INFO/ForkPoolWorker-8] Task websecmap.app.models.create_function_job[3574e7c3-6ac7-4f38-88f2-2041051bc251] succeeded in 4.220241545001045s: <Job: dashboard.internet_nl_dashboard.tasks.start_scans_for_lists_who_are_up_for_scanning>
[2020-10-05 14:18:04,236: WARNING/ForkPoolWorker-8] Exception ignored in:
[2020-10-05 14:18:04,236: WARNING/ForkPoolWorker-8] <function AsyncResult.__del__ at 0x7fc177b34b00>
2020-10-05 14:18	INFO     - Task websecmap.app.models.store_result[8c282899-3fdd-4d00-b706-8d5f09d1ec14] succeeded in 0.024128417018800974s: None
[2020-10-05 14:18:04,236: WARNING/ForkPoolWorker-8] Traceback (most recent call last):
[2020-10-05 14:18:04,236: INFO/ForkPoolWorker-9] Task websecmap.app.models.store_result[8c282899-3fdd-4d00-b706-8d5f09d1ec14] succeeded in 0.024128417018800974s: None
[2020-10-05 14:18:04,236: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 389, in __del__
[2020-10-05 14:18:04,237: WARNING/ForkPoolWorker-8] self.backend.remove_pending_result(self)
[2020-10-05 14:18:04,237: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 180, in remove_pending_result
[2020-10-05 14:18:04,237: WARNING/ForkPoolWorker-8] self.on_result_fulfilled(result)
[2020-10-05 14:18:04,238: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 188, in on_result_fulfilled
[2020-10-05 14:18:04,238: WARNING/ForkPoolWorker-8] self.result_consumer.cancel_for(result.id)
[2020-10-05 14:18:04,238: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/redis.py", line 148, in cancel_for
[2020-10-05 14:18:04,238: WARNING/ForkPoolWorker-8] self._pubsub.unsubscribe(key)
[2020-10-05 14:18:04,239: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3548, in unsubscribe
[2020-10-05 14:18:04,240: WARNING/ForkPoolWorker-8] return self.execute_command('UNSUBSCRIBE', *args)
[2020-10-05 14:18:04,241: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3423, in execute_command
[2020-10-05 14:18:04,243: WARNING/ForkPoolWorker-8] self._execute(connection, connection.send_command, *args, **kwargs)
[2020-10-05 14:18:04,243: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute
[2020-10-05 14:18:04,246: WARNING/ForkPoolWorker-8] return command(*args, **kwargs)
[2020-10-05 14:18:04,246: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 721, in send_command
2020-10-05 14:18	DEBUG    - On 2020-07-29 05:47:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
[2020-10-05 14:18:04,250: DEBUG/ForkPoolWorker-1] On 2020-07-29 05:47:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
[2020-10-05 14:18:04,252: WARNING/ForkPoolWorker-8] check_health=kwargs.get('check_health', True))
[2020-10-05 14:18:04,252: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 713, in send_packed_command
[2020-10-05 14:18:04,252: WARNING/ForkPoolWorker-8] (errno, errmsg))
[2020-10-05 14:18:04,253: WARNING/ForkPoolWorker-8] redis.exceptions
[2020-10-05 14:18:04,253: WARNING/ForkPoolWorker-8] .
[2020-10-05 14:18:04,253: WARNING/ForkPoolWorker-8] ConnectionError
[2020-10-05 14:18:04,253: WARNING/ForkPoolWorker-8] :
[2020-10-05 14:18:04,253: WARNING/ForkPoolWorker-8] Error 104 while writing to socket. Connection reset by peer.
2020-10-05 14:18	DEBUG    - On 2020-07-29 11:30:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
[2020-10-05 14:18:04,268: DEBUG/ForkPoolWorker-1] On 2020-07-29 11:30:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
2020-10-05 14:18	DEBUG    - On 2020-07-29 12:01:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
[2020-10-05 14:18:04,283: DEBUG/ForkPoolWorker-1] On 2020-07-29 12:01:59.999999+00:00 www.alkmaar.nl has 2 endpoints.
2020-10-05 14:18	DEBUG    - On 2020-07-29 14:06:59.999999+00:00 www.alkmaar.nl has 2 endpoints.


2020-10-05 14:22	DEBUG    - On 2020-08-10 05:09:59.999999+00:00 www.landsmeer.nl has 2 endpoints.
[2020-10-05 14:22:01,355: DEBUG/ForkPoolWorker-1] On 2020-08-10 05:09:59.999999+00:00 www.landsmeer.nl has 2 endpoints.
[2020-10-05 14:22:01,362: INFO/MainProcess] Received task: websecmap.app.models.create_function_job[bc6676e4-8096-4237-ba28-c9a04cb18b84]  
[2020-10-05 14:22:01,362: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fc176171cb0> (args:('websecmap.app.models.create_function_job', 'bc6676e4-8096-4237-ba28-c9a04cb18b84', {'lang': 'py', 'task': 'websecmap.app.models.create_function_job', 'id': 'bc6676e4-8096-4237-ba28-c9a04cb18b84', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'bc6676e4-8096-4237-ba28-c9a04cb18b84', 'parent_id': None, 'argsrepr': "['dashboard.internet_nl_dashboard.tasks.start_scans_for_lists_who_are_up_for_scanning']", 'kwargsrepr': '{}', 'origin': 'gen1@b67fb3c544b5', 'reply_to': '693ba0a1-fbcf-301a-a4e1-5ff65725a5d6', 'correlation_id': 'bc6676e4-8096-4237-ba28-c9a04cb18b84', 'hostname': 'default@14ed9ae498f6', 'delivery_info': {'exchange': '', 'routing_key': 'storage', 'priority': 5, 'redelivered': None}, 'args': ['dashboard.internet_nl_dashboard.tasks.start_scans_for_lists_who_are_up_for_scanning'], 'kwargs': {}},... kwargs:{})
[2020-10-05 14:22:01,369: DEBUG/MainProcess] Task accepted: websecmap.app.models.create_function_job[bc6676e4-8096-4237-ba28-c9a04cb18b84] pid:444
2020-10-05 14:22	DEBUG    - On 2020-08-10 05:54:59.999999+00:00 www.landsmeer.nl has 2 endpoints.
[2020-10-05 14:22:01,391: DEBUG/ForkPoolWorker-1] On 2020-08-10 05:54:59.999999+00:00 www.landsmeer.nl has 2 endpoints.
[2020-10-05 14:22:01,397: WARNING/ForkPoolWorker-8] Exception ignored in:
[2020-10-05 14:22:01,399: WARNING/ForkPoolWorker-8] <function AsyncResult.__del__ at 0x7fc177b34b00>
[2020-10-05 14:22:01,399: WARNING/ForkPoolWorker-8] Traceback (most recent call last):
[2020-10-05 14:22:01,399: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 389, in __del__
[2020-10-05 14:22:01,399: WARNING/ForkPoolWorker-8] self.backend.remove_pending_result(self)
[2020-10-05 14:22:01,399: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 180, in remove_pending_result
[2020-10-05 14:22:01,400: WARNING/ForkPoolWorker-8] self.on_result_fulfilled(result)
[2020-10-05 14:22:01,400: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 188, in on_result_fulfilled
[2020-10-05 14:22:01,400: WARNING/ForkPoolWorker-8] self.result_consumer.cancel_for(result.id)
[2020-10-05 14:22:01,400: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/redis.py", line 148, in cancel_for
[2020-10-05 14:22:01,400: WARNING/ForkPoolWorker-8] self._pubsub.unsubscribe(key)
[2020-10-05 14:22:01,400: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3548, in unsubscribe
[2020-10-05 14:22:01,402: WARNING/ForkPoolWorker-8] return self.execute_command('UNSUBSCRIBE', *args)
[2020-10-05 14:22:01,405: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3423, in execute_command
[2020-10-05 14:22:01,406: WARNING/ForkPoolWorker-8] self._execute(connection, connection.send_command, *args, **kwargs)
[2020-10-05 14:22:01,406: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute
[2020-10-05 14:22:01,408: WARNING/ForkPoolWorker-8] return command(*args, **kwargs)
[2020-10-05 14:22:01,408: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 721, in send_command
[2020-10-05 14:22:01,409: WARNING/ForkPoolWorker-8] check_health=kwargs.get('check_health', True))
[2020-10-05 14:22:01,409: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 713, in send_packed_command
[2020-10-05 14:22:01,409: WARNING/ForkPoolWorker-8] (errno, errmsg))
2020-10-05 14:22	DEBUG    - On 2020-08-12 04:53:59.999999+00:00 www.landsmeer.nl has 2 endpoints.
[2020-10-05 14:22:01,409: WARNING/ForkPoolWorker-8] redis.exceptions
[2020-10-05 14:22:01,409: DEBUG/ForkPoolWorker-1] On 2020-08-12 04:53:59.999999+00:00 www.landsmeer.nl has 2 endpoints.
[2020-10-05 14:22:01,410: WARNING/ForkPoolWorker-8] .
[2020-10-05 14:22:01,410: WARNING/ForkPoolWorker-8] ConnectionError
[2020-10-05 14:22:01,410: WARNING/ForkPoolWorker-8] :
[2020-10-05 14:22:01,410: WARNING/ForkPoolWorker-8] Error 104 while writing to socket. Connection reset by peer.
2020-10-05 14:22	DEBUG    - On 2020-08-12 05:27:59.999999+00:00 www.landsmeer.nl has 2 endpoints.
[2020-10-05 14:22:01,430: DEBUG/ForkPoolWorker-1] On 2020-08-12 05:27:59.999999+00:00 www.landsmeer.nl has 2 endpoints.


2020-10-05 14:23	INFO     - Task websecmap.reporting.report.recreate_url_reports[91bf6373-d3eb-4664-aa1a-c9bea848dccd] succeeded in 462.8557004739996s: None
[2020-10-05 14:23:45,566: INFO/ForkPoolWorker-1] Task websecmap.reporting.report.recreate_url_reports[91bf6373-d3eb-4664-aa1a-c9bea848dccd] succeeded in 462.8557004739996s: None
[2020-10-05 14:23:45,567: INFO/MainProcess] Received task: dashboard.internet_nl_dashboard.logic.urllist_dashboard_report.create_dashboard_report[4ccef61c-ae11-4353-abd9-9efb08c52d67]  
[2020-10-05 14:23:45,579: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fc176171cb0> (args:('dashboard.internet_nl_dashboard.logic.urllist_dashboard_report.create_dashboard_report', '4ccef61c-ae11-4353-abd9-9efb08c52d67', {'lang': 'py', 'task': 'dashboard.internet_nl_dashboard.logic.urllist_dashboard_report.create_dashboard_report', 'id': '4ccef61c-ae11-4353-abd9-9efb08c52d67', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '8f7e350b-7e61-4b96-933b-a4651358b226', 'parent_id': '91bf6373-d3eb-4664-aa1a-c9bea848dccd', 'argsrepr': '(<UrlList: rob.vanlinden/www.domein.nl>,)', 'kwargsrepr': '{}', 'origin': 'gen437@14ed9ae498f6', 'reply_to': '7429300e-b133-31c4-b08e-7c022bb0d5b5', 'correlation_id': '4ccef61c-ae11-4353-abd9-9efb08c52d67', 'hostname': 'default@14ed9ae498f6', 'delivery_info': {'exchange': '', 'routing_key': 'storage', 'priority': 5, 'redelivered': None}, 'args': (<UrlList: rob.vanlinden/www.domein.nl>,), 'kwargs': {}},... kwargs:{})
2020-10-05 14:23	INFO     - Creating report for urllist rob.vanlinden/www.domein.nl on 2020-10-05 14:24:45.582729+00:00
[2020-10-05 14:23:45,582: INFO/ForkPoolWorker-8] Creating report for urllist rob.vanlinden/www.domein.nl on 2020-10-05 14:24:45.582729+00:00
[2020-10-05 14:23:45,584: DEBUG/MainProcess] Task accepted: dashboard.internet_nl_dashboard.logic.urllist_dashboard_report.create_dashboard_report[4ccef61c-ae11-4353-abd9-9efb08c52d67] pid:444
[2020-10-05 14:23:46,135: WARNING/ForkPoolWorker-8] Exception ignored in:
[2020-10-05 14:23:46,135: WARNING/ForkPoolWorker-8] <function AsyncResult.__del__ at 0x7fc177b34b00>
[2020-10-05 14:23:46,135: WARNING/ForkPoolWorker-8] Traceback (most recent call last):
[2020-10-05 14:23:46,135: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/result.py", line 389, in __del__
[2020-10-05 14:23:46,135: WARNING/ForkPoolWorker-8] self.backend.remove_pending_result(self)
[2020-10-05 14:23:46,136: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 180, in remove_pending_result
[2020-10-05 14:23:46,136: WARNING/ForkPoolWorker-8] self.on_result_fulfilled(result)
[2020-10-05 14:23:46,136: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 188, in on_result_fulfilled
[2020-10-05 14:23:46,136: WARNING/ForkPoolWorker-8] self.result_consumer.cancel_for(result.id)
[2020-10-05 14:23:46,136: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/celery/backends/redis.py", line 148, in cancel_for
[2020-10-05 14:23:46,136: WARNING/ForkPoolWorker-8] self._pubsub.unsubscribe(key)
[2020-10-05 14:23:46,137: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3548, in unsubscribe
[2020-10-05 14:23:46,138: WARNING/ForkPoolWorker-8] return self.execute_command('UNSUBSCRIBE', *args)
[2020-10-05 14:23:46,138: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3423, in execute_command
[2020-10-05 14:23:46,139: WARNING/ForkPoolWorker-8] self._execute(connection, connection.send_command, *args, **kwargs)
[2020-10-05 14:23:46,139: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute
[2020-10-05 14:23:46,140: WARNING/ForkPoolWorker-8] return command(*args, **kwargs)
[2020-10-05 14:23:46,140: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 721, in send_command
[2020-10-05 14:23:46,141: WARNING/ForkPoolWorker-8] check_health=kwargs.get('check_health', True))
[2020-10-05 14:23:46,141: WARNING/ForkPoolWorker-8] File "/pyenv/lib/python3.7/site-packages/redis/connection.py", line 713, in send_packed_command
[2020-10-05 14:23:46,141: WARNING/ForkPoolWorker-8] (errno, errmsg))
[2020-10-05 14:23:46,142: WARNING/ForkPoolWorker-8] redis.exceptions
[2020-10-05 14:23:46,142: WARNING/ForkPoolWorker-8] .
[2020-10-05 14:23:46,142: WARNING/ForkPoolWorker-8] ConnectionError
[2020-10-05 14:23:46,142: WARNING/ForkPoolWorker-8] :
[2020-10-05 14:23:46,142: WARNING/ForkPoolWorker-8] Error 104 while writing to socket. Connection reset by peer.
2020-10-05 14:23	INFO     - The calculation for rob.vanlinden/www.domein.nl on 2020-10-05 14:24:45.582729+00:00 has changed, so we're saving this rating.
[2020-10-05 14:23:48,149: INFO/ForkPoolWorker-8] The calculation for rob.vanlinden/www.domein.nl on 2020-10-05 14:24:4

```

**Comment by stitch** [comment]
Solved with last bug fixes.
